version: '3.8'
services:
  mockable-server:
    build:
      context: .

  testing:
    build:
      context: .
      target: test
    environment:
      TEST_MOCKABLE_SERVER_BASE: http://mockable-server:8010
      TEST_MOCKABLE_SERVER_CONTROL_BASE: http://mockable-server:8020
    depends_on:
      - mockable-server
