version: '3.6'
services:
  mockable-server:
    build:
      context: .

  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: .
      target: test
    environment:
      TEST_MOCKABLE_SERVER_BASE: http://mockable-server:8010
      TEST_MOCKABLE_SERVER_CONTROL_BASE: http://mockable-server:8020
    depends_on:
      - mockable-server
