name: DockerHub Description

on:
  push:
    branches:
      - 'master'
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: spuf/mockable-server
        short-description: ${{ github.event.repository.description }}
